### ISSUE TITLE
Fix IobEncoding

### ISSUE THREAD

**Issue by neumannm** [openminted/uc-tdm-socialsciences#21]
MyIobEncoder is not working a 100% correctly. Have to make sure that overlapping, nested and adjacent annotations are handled. Although not all of these cases might happen in the actual data, the encoder should still cover all these cases.

**Comment by neumannm** [comment]
To this end, I need to know exactly how to access this information about nested/overlapping annotations. For example, there are `CasUtil.indexCovering(CAS cas, Type type, Type coveringType)` as well as `CasUtil.indexCovered(CAS cas, Type type, Type coveredType)` methods. I'm not sure how they relate to overlapping annotations. For nested annotations, it's clear. I can check if one annotation covers a collection of other annotations. 

But what if there are overlaps? What if there is annotation A from 1-4 and annotation B from 3-6? What will be in the index for index.get(A) and index.get(B)? Can anybody help?

**Comment by reckart** [comment]
uimaFIT (J)CasUtil does currently not have support for overlapping annotations. indexCovering and indexCovered do not include overlapping annotations at the edges - only properly contained/covering annotations. You could try to copying/adapting the code of the respective uimaFIT methods to also handle overlapping annotations.

**Comment by greenwoodma** [comment]
Really? If that is the case and the format can't handle overlapping annotations then we need to look for another annotation representation that we can use as we can't just ignore a whole bunch of possible annotations. We can't know in advance what annotations people might want to use or create so we must be using a representation that can handle any combination of annotations, including overlapping.

**Comment by reckart** [comment]
@greenwoodma correct me if I am wrong, but usually sequence classifiers cannot be trained on overlapping spans.

**Comment by greenwoodma** [comment]
@reckart that's probably true (I certainly can't think of one off the top of my head) but surely we aren't limiting ourselves to just single sequence labelling problems? It's very easy to produce sets of annotations that partially overlap in any text mining application so we should ensure that _any_ representation we use can handle them otherwise we run the risk of losing data. For example, while we offer inline XML in GATE we don't use it very often specifically as it can't handle overlapping annotations so we use GATE XML which is lossless.

**Comment by neumannm** [comment]
"indexCovering and indexCovered do not include overlapping annotations at the edges - only properly contained/covering annotations."

So what exactly happens if there is annotation A from 1-4 and annotation B from 3-6 when I try to create an index of these annotations? Will neither of these be included? 

Regarding your discussion, it's not that the format can't handle overlapping annotations (because it can). It's just that I need to transform the annotations for the sequence labelling and thus just in case there are overlaps, I want to make sure that they are either ignored, or just one of those annotations will be included. So that input with overlapping annotated named entities will not break the system.

**Comment by reckart** [comment]
If you index/select the annotations covered by A (1-4) then B (3-6) will not be included.
If you index/select the annotations covering B (3-6) then A(1-4) will not be included.

It's not that you couldn't find such annotations using UIMA, but uimaFIT doesn't offer convenience methods (yet) that consider overlaps.

**Comment by greenwoodma** [comment]
so if uimaFIT doesn't handle these (yet) we should probably advise people to avoid it (at least for now) so that the issues we've just had don't bite anyone else, especially as it's not always obvious that you've lost annotations in this kind of situation. Personally I would consider any format/lib that can't handle overlapping annotations dangerously defective.

**Comment by reckart** [comment]
@greenwoodma uimaFIT is a convenience API on top of UIMA. Mandy and Masoud use it because it's easier. Actual users (i.e. non-developers) would hardly ever come into contact with it. The question IMHO not whether uimaFIT has any support for conveniently retrieving overlapping annotations, but rather if and how such annotations could serve to train a CRF named entity classifier (specifically Standford) - and that I don't see. 

if two different types of NEs overlap, then one could train separate classifiers for each type and be done with it. However, if a person overlaps with a person, then this is something that afaik the kind of NER tool that we are using here simply does not support.

**Comment by greenwoodma** [comment]
@reckart yes I know it's only developers that will come into contact with uimaFIT but as we've just seen it can be confusing to find that not all annotations are retrieved correctly, and this could cause issues for other component developers. We have numerous requirements now that make suggestions to developers on the way things should be done (mostly around metadata not code I admit) and a working group on annotations. All I'd suggest is that somewhere in amongst all that we make a recommendation that uimaFIT should possibly be avoided due to it being unable to accurately represent/retrieve all annotations that may be present within a document; being unable to do so is clearly a serious defect.

As to two different types of NE overlapping then yes you could train to different classifiers but what about the component that comes next? Maybe that takes the output from the two classifiers to do something else. In those cases overlapping annotations is a real concern. For example you could have one classifier for people, one for orgnizations, and one for locations. On their own there is no problem, but what happens when you want to start looking at the annotations? These three types can easily overlap on just the way uimaFIT doesn't support.

**Comment by neumannm** [comment]
"If you index/select the annotations covered by A (1-4) then B (3-6) will not be included.
If you index/select the annotations covering B (3-6) then A(1-4) will not be included."

Ok good I think I can work with that. 
Btw @reckart is it normal that with `indexCovered` you map each annotation to itself? So I have an example sentence with 4 annotations. With `indexCovered` I have 4 entries in this index, one for each annotation, three of them having only itself as value and only one has two values because there is actually a nested annotation. When using `indexCovering`, I get only one entry for this nested annotation. I find this quite confusing.

**Comment by reckart** [comment]
@greenwoodma that really depends on the following component and if/how underlying tools handle overlaps. it doesn't really depend on at all uimaFIT.

**Comment by reckart** [comment]
> Btw @reckart is it normal that with indexCovered you map each annotation to itself? So I have an example sentence with 4 annotations. With indexCovered I have 4 entries in this index, one for each annotation, three of them having only itself as value and only one has two values because there is actually a nested annotation. When using indexCovering, I get only one entry for this nested annotation. I find this quite confusing.

Sounds like a bug / underspecification in uimaFIT. So you say `indexCovering` and `indexCovered` behave inconsistently?

**Comment by greenwoodma** [comment]
@reckart yes and no. Certainly if the document contains (or could contain) overlapping annotations then you would want to avoid developing/using a component that couldn't access them all correctly; i.e. you would want to avoid uimaFIT

**Comment by neumannm** [comment]
Well in my intuition I would not expect this behavior I just described. If this is a potential bug maybe we should discuss this elsewhere?

**Comment by reckart** [comment]
@greenwoodma *sigh* if you want to get annotations from a document using uimaFIT, you usually use something like `select(doc, NamedEntity.class)` and that works in all cases - overlapping or not. The most common use of `selectCovered` is `selectCovered(someSentence, NamedEntity.class)` which also works fine - I cannot remember ever having met anybody who was interested in this call also returning overlapping annotations. If you wanted to find specifically overlapping annotations, you'd so something like 

```
List<NamedEntity> overlappers = new ArrayList<>();
for (NamedEntity x : select(doc, NamedEntity.class) { // <= uimaFIT select
  for (NamedEntity y : select(doc, NamedEntity.class) { // <= uimaFIT select
    if (overlaps(x, y)) { // implementation of the overlaps() method is left to your imagination
     overlappers.add(y);
   }
  }
}
```

This works, but it is not terribly fast. There is no reason why you would want to avoid uimaFIT or what uimaFIT would not support working with annotations that overlap. But there is no optimized and convenient method variant of the `select` methods that explicitly deals with overlapping annotations.

**Comment by greenwoodma** [comment]
@reckart that all makes perfect sense. I still worry that people will expect the convenience methods to return all annotations which should logical match, but at least there is a sensible way to get at those annotations as long as you understand the shortcomings of the uimaFIT lib.

**Comment by reckart** [comment]
It is not a shortcoming of uimaFIT, it is a design choice!

**Comment by reckart** [comment]
If you design a system in such a way that "covered" is defined as "properly covered" then it is perfectly ok that it does not return overlapping stuff.

**Comment by greenwoodma** [comment]
That's true and you are right a perfectly acceptable design choice. I guess I just assumed this wasn't the intended design due to the initial discussion; as long as the method is correctly documented I see no problem with it, especially as you can access those "missing" annotations in another way.

**Comment by reckart** [comment]
I'll make sure that's explicitly covered in the documentation in the next release: https://issues.apache.org/jira/browse/UIMA-5247

**Comment by maxxkia** [comment]
@neumannm This bug is fixed, right?

**Comment by neumannm** [comment]
Yes I think so. So nested annotations are handled (only outmost is encoded), for overlapping the second annotation should be ignored (although I don't expect that case even to happen), and sub-token annotations should also be ignored now. Because IOB encoding doesn't make sense for them either.
